#ifndef CYGONCE_PKGCONF_DEVS_ETH_MIPS_RA305X_H
#define CYGONCE_PKGCONF_DEVS_ETH_MIPS_RA305X_H
/*
 * File <pkgconf/devs_eth_mips_ra305x.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */
#define CYGDBG_DEVS_ETH_MIPS_RA305X_CHATTER 1

#define CYGNUM_DEVS_ETH_MIPS_RA305X_RX_RING_SIZE 64
#define CYGNUM_DEVS_ETH_MIPS_RA305X_RX_RING_SIZE_64
#define CYGNUM_DEVS_ETH_MIPS_RA305X_TX_RING_SIZE 128
#define CYGNUM_DEVS_ETH_MIPS_RA305X_TX_RING_SIZE_128
#define CYGNUM_DEVS_ETH_MIPS_RA305X_DEV_COUNT 2
#define CYGNUM_DEVS_ETH_MIPS_RA305X_DEV_COUNT_2
#define CYGPKG_DEVS_ETH_MIPS_RA305X_ETH0 1
#define CYGDAT_DEVS_ETH_MIPS_RA305X_ETH0_NAME "eth0"
#define CYGNUM_DEVS_ETH_MIPS_RA305X_ETH0_PORTMASK 30
#define CYGNUM_DEVS_ETH_MIPS_RA305X_ETH0_PORTMASK_30
#define CYGSEM_DEVS_ETH_MIPS_RA305X_ETH0_SET_ESA 1
#define CYGDAT_DEVS_ETH_MIPS_RA305X_ETH0_ESA {0x00, 0xaa, 0xde, 0xad, 0xbe, 0xef}
#define CYGPKG_DEVS_ETH_MIPS_RA305X_ETH1 1
#define CYGDAT_DEVS_ETH_MIPS_RA305X_ETH1_NAME "eth1"
#define CYGNUM_DEVS_ETH_MIPS_RA305X_ETH1_PORTMASK 1
#define CYGNUM_DEVS_ETH_MIPS_RA305X_ETH1_PORTMASK_1
#define CYGSEM_DEVS_ETH_MIPS_RA305X_ETH1_SET_ESA 1
#define CYGDAT_DEVS_ETH_MIPS_RA305X_ETH1_ESA {0x00, 0xab, 0xde, 0xad, 0xbe, 0xef}
#endif
