#ifndef CYGONCE_PKGCONF_NET_FREEBSD_STACK_H
#define CYGONCE_PKGCONF_NET_FREEBSD_STACK_H
/*
 * File <pkgconf/net_freebsd_stack.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#include <pkgconf/net.h>
#define CYGINT_NET_IPSEC_BSD_CRYPTO 1
#define CYGINT_NET_IPSEC_BSD_CRYPTO_1
#define CYGPKG_NET_NGIF 0
#define CYGPKG_NET_NGIF_0
#define NGIF 0
#define NGIF_0
#define CYGPKG_NET_NLOOP 1
#define CYGPKG_NET_NLOOP_1
#define NLOOP 1
#define NLOOP_1
#define CYGPKG_NET_FREEBSD_LOGGING 0x0000C08F
#define CYGPKG_NET_FREEBSD_LOGGING_0x0000C08F
#define CYGPKG_NET_MEM_USAGE 262144
#define CYGPKG_NET_MEM_USAGE_262144
#define CYGPKG_NET_MEMPOOL_SIZE 1048576 //1024*1024
#define CYGPKG_NET_MEMPOOL_SIZE_1048576
#define CYGPKG_NET_MAXSOCKETS 256
#define CYGPKG_NET_MAXSOCKETS_128
#define CYGPKG_NET_NUM_WAKEUP_EVENTS 8
#define CYGPKG_NET_NUM_WAKEUP_EVENTS_8
#define CYGPKG_NET_THREAD_PRIORITY 7
#define CYGPKG_NET_THREAD_PRIORITY_7
#define CYGNUM_NET_THREAD_STACKSIZE CYGNUM_HAL_STACK_SIZE_TYPICAL
#define CYGNUM_NET_THREAD_STACKSIZE_CYGNUM_HAL_STACK_SIZE_TYPICAL
#define CYGPKG_NET_FAST_THREAD_PRIORITY 6
#define CYGPKG_NET_FAST_THREAD_PRIORITY_6
#define CYGNUM_NET_FAST_THREAD_STACKSIZE CYGNUM_HAL_STACK_SIZE_TYPICAL
#define CYGNUM_NET_FAST_THREAD_STACKSIZE_CYGNUM_HAL_STACK_SIZE_TYPICAL
#define CYGPKG_NET_FAST_THREAD_TICKLE_DEVS 1
#define CYGNUM_NET_FAST_THREAD_TICKLE_DEVS_DELAY 50
#define CYGNUM_NET_FAST_THREAD_TICKLE_DEVS_DELAY_50
//Add by Eddy
#define CYGNUM_NET_BRIDGES 1
#define CYGNUM_NET_BRIDGES_1
#define CYGPKG_NET_IPSEC_LIBIPSEC 1
#define CYGPKG_NET_IPSEC_LIBIPSEC_1
#define CYGPKG_OPENSSL_SHA 1
#define CYGPKG_OPENSSL_SHA1 1
#define CYGPKG_OPENSSL_MD5 1
#define CYGPKG_OPENSSL_MDC2 1
#define CYGPKG_OPENSSL_DES 1
#define CYGPKG_OPENSSL_MD2 1
#endif
