/****************************************************************************
 * Ralink Tech Inc.
 * Taiwan, R.O.C.
 *
 * (c) Copyright 2002, Ralink Technology, Inc.
 *
 * All rights reserved. Ralink's source code is an unpublished work and the
 * use of a copyright notice does not imply otherwise. This source code
 * contains confidential trade secret material of Ralink Tech. Any attemp
 * or participation in deciphering, decoding, reverse engineering or in any
 * way altering the source code is stricitly prohibited, unless the prior
 * written consent of Ralink Technology, Inc. is obtained.
 ***************************************************************************/

#include <upnp.h>
/*
static char xml_template[] =
(
	"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
	"<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\r\n"
	"<specVersion>\r\n"
	"<major>1</major>\r\n"
	"<minor>0</minor>\r\n"
	"</specVersion>\r\n"
	"<actionList>\r\n"
	"<action>\r\n"
	"<name>DelAPSettings</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewAPSettings</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>APSettings</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>DelSTASettings</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewSTASettings</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>STASettings</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>GetAPSettings</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewMessage</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>Message</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"<argument>\r\n"
	"<name>NewAPSettings</name>\r\n"
	"<direction>out</direction>\r\n"
	"<relatedStateVariable>APSettings</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>GetDeviceInfo</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewDeviceInfo</name>\r\n"
	"<direction>out</direction>\r\n"
	"<relatedStateVariable>DeviceInfo</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>GetSTASettings</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewMessage</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>Message</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"<argument>\r\n"
	"<name>NewSTASettings</name>\r\n"
	"<direction>out</direction>\r\n"
	"<relatedStateVariable>STASettings</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>PutMessage</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewInMessage</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>InMessage</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"<argument>\r\n"
	"<name>NewOutMessage</name>\r\n"
	"<direction>out</direction>\r\n"
	"<relatedStateVariable>OutMessage</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>PutWLANResponse</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewMessage</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>Message</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"<argument>\r\n"
	"<name>NewWLANEventType</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>WLANEventType</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"<argument>\r\n"
	"<name>NewWLANEventMAC</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>WLANEventMAC</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>RebootAP</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewAPSettings</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>APSettings</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>RebootSTA</name>\r\n"
	"<argumentList>\r\n"
	"<argument><name>NewSTASettings</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>APSettings</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>ResetAP</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewMessage</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>Message</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>ResetSTA</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewMessage</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>Message</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>SetAPSettings</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>APSettings</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>APSettings</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>SetSelectedRegistrar</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewMessage</name>\r\n"
	"<direction>in</direction>\r\n"
	"<relatedStateVariable>Message</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"<action>\r\n"
	"<name>SetSTASettings</name>\r\n"
	"<argumentList>\r\n"
	"<argument>\r\n"
	"<name>NewSTASettings</name>\r\n"
	"<direction>out</direction>\r\n"
	"<relatedStateVariable>STASettings</relatedStateVariable>\r\n"
	"</argument>\r\n"
	"</argumentList>\r\n"
	"</action>\r\n"
	"</actionList>\r\n"
	"\r\n"
	"<serviceStateTable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>WLANResponse</name>\r\n"
	"<dataType>bin.base64</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>Message</name>\r\n"
	"<dataType>bin.base64</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>WLANEventType</name>\r\n"
	"<dataType>ui1</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>WLANEventMAC</name>\r\n"
	"<dataType>string</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"yes\">\r\n"
	"<name>WLANEvent</name>\r\n"
	"<dataType>bin.base64</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>DeviceInfo</name>\r\n"
	"<dataType>bin.base64</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>STASettings</name>\r\n"
	"<dataType>bin.base64</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>APSettings</name>\r\n"
	"<dataType>bin.base64</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"yes\">\r\n"
	"<name>APStatus</name>\r\n"
	"<dataType>ui1</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"yes\">\r\n"
	"<name>STAStatus</name>\r\n"
	"<dataType>ui1</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>InMessage</name>\r\n"
	"<dataType>bin.base64</dataType>\r\n"
	"</stateVariable>\r\n"
	"<stateVariable sendEvents=\"no\">\r\n"
	"<name>OutMessage</name>\r\n"
	"<dataType>bin.base64</dataType>\r\n"
	"</stateVariable>\r\n"
	"</serviceStateTable>\r\n"
	"</scpd>\r\n"
	"\r\n"
);
*/
int xml_x_wfawlanconfigscpd(UPNP_CONTEXT * context)
{
    int len;    
	char* pInternetGatewayDevice=NULL;
	int result=0;
	
	result = description_readXML(XML_INDEX_x_wfawlanconfigscpd,&pInternetGatewayDevice,&len);
	
	if(pInternetGatewayDevice==NULL || result==0) return 1;
	
	CONTEXT_SEND(pInternetGatewayDevice, len);
	
	if(pInternetGatewayDevice!=NULL) 
	{	
		free(pInternetGatewayDevice);
		pInternetGatewayDevice=NULL;
	}
	
	return 0;
}

