#!/bin/bash
source ../.config


printhead()
{
	echo "/*" >> $filename
 	echo " * Generated by Ralink upnp XML converter:`date`" >> $filename
 	echo " * Do not edit" >> $filename
 	echo " */" >> $filename
}




#generate upnpxmldata.bin first
#here generate XML templete sequence in upnpxmldata.bin when generate upnpxmldata.bin
#so make sure that XML_INDEX enum in upnp_description.h according with XML templete sequence in upnpxmldata.bin
	#cp xmldata/InternetGatewayDevice.xml xmldata/InternetGatewayDevice.bin
	../../../tools/bin/lzma e xmldata_wps/InternetGatewayDevice.xml xmldata_wps/InternetGatewayDevice.bin -d16
	cat xmldata_wps/InternetGatewayDevice.bin >> ../upnpxmldata.bin
	#cp xmldata/x_lanhostconfigmanagement.xml xmldata/x_lanhostconfigmanagement.bin
	../../../tools/bin/lzma e xmldata_wps/x_lanhostconfigmanagement.xml xmldata_wps/x_lanhostconfigmanagement.bin -d16
	cat xmldata_wps/x_lanhostconfigmanagement.bin >> ../upnpxmldata.bin
	#cp xmldata/x_layer3forwarding.xml xmldata/x_layer3forwarding.bin
	../../../tools/bin/lzma e xmldata_wps/x_layer3forwarding.xml xmldata_wps/x_layer3forwarding.bin -d16
	cat xmldata_wps/x_layer3forwarding.bin >> ../upnpxmldata.bin
	#cp xmldata/x_wancommoninterfaceconfig.xml xmldata/x_wancommoninterfaceconfig.bin
	../../../tools/bin/lzma e xmldata_wps/x_wancommoninterfaceconfig.xml xmldata_wps/x_wancommoninterfaceconfig.bin -d16
	cat xmldata_wps/x_wancommoninterfaceconfig.bin >> ../upnpxmldata.bin
	#cp xmldata/x_wanipconnection.xml xmldata/x_wanipconnection.bin
	../../../tools/bin/lzma e xmldata_wps/x_wanipconnection.xml xmldata_wps/x_wanipconnection.bin -d16
	cat xmldata_wps/x_wanipconnection.bin >> ../upnpxmldata.bin
	#cp xmldata/x_wfadevicedesc.xml xmldata/x_wfadevicedesc.bin
	../../../tools/bin/lzma e xmldata_wps/x_wfadevicedesc.xml xmldata_wps/x_wfadevicedesc.bin -d16
	cat xmldata_wps/x_wfadevicedesc.bin >> ../upnpxmldata.bin
	#cp xmldata/x_wfawlanconfigscpd.xml xmldata/x_wfawlanconfigscpd.bin
	../../../tools/bin/lzma e xmldata_wps/x_wfawlanconfigscpd.xml xmldata_wps/x_wfawlanconfigscpd.bin -d16
	cat xmldata_wps/x_wfawlanconfigscpd.bin >> ../upnpxmldata.bin
	#cp xmldata/x_wfadevicedesc.xml xmldata/x_wfadevicedesc.bin
	../../../tools/bin/lzma e xmldata_wps/x_wfa5Gdevicedesc.xml xmldata_wps/x_wfa5Gdevicedesc.bin -d16
	cat xmldata_wps/x_wfa5Gdevicedesc.bin >> ../upnpxmldata.bin	
	#cp xmldata/x_wfawlanconfigscpd.xml xmldata/x_wfawlanconfigscpd.bin
	../../../tools/bin/lzma e xmldata_wps/x_wfa5Gwlanconfigscpd.xml xmldata_wps/x_wfa5Gwlanconfigscpd.bin -d16
	cat xmldata_wps/x_wfa5Gwlanconfigscpd.bin >> ../upnpxmldata.bin
	#cp xmldata/InternetGatewayDevice.xml xmldata/InternetGatewayDevice.bin
	../../../tools/bin/lzma e xmldata_wps/InternetGatewayDevice2WLAN.xml xmldata_wps/InternetGatewayDevice2WLAN.bin -d16
	cat xmldata_wps/InternetGatewayDevice2WLAN.bin >> ../upnpxmldata.bin
		
#generate xmldata.c
filename=xmldata.c

printhead

echo "#include \"xml_data.h\"" >> $filename
echo "#include \"include/upnp_description.h\"" >> $filename
#echo "#include \"web_config.h\"" >> $filename

echo >> $filename
#echo "time_t time_pages_created =(`date +%s`+28800);"  >> $filename

echo "extern char _binary_upnpxmldata_bin_start[];" >> $filename
echo "char *upnpxmldata_location = &_binary_upnpxmldata_bin_start[0];" >> $filename


echo >> $filename

echo "upnpxmldata_entry upnpxmldata_table[]= {" >> $filename

echo "{XML_INDEX_InternetGatewayDevice, " >> $filename
echo "`stat -t xmldata_wps/InternetGatewayDevice.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_x_lanhostconfigmanagement, " >> $filename
echo "`stat -t xmldata_wps/x_lanhostconfigmanagement.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_x_layer3forwarding, " >> $filename
echo "`stat -t xmldata_wps/x_layer3forwarding.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_x_wancommoninterfaceconfig, " >> $filename
echo "`stat -t xmldata_wps/x_wancommoninterfaceconfig.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_x_wanipconnection, " >> $filename
echo "`stat -t xmldata_wps/x_wanipconnection.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_x_wfadevicedesc, " >> $filename
echo "`stat -t xmldata_wps/x_wfadevicedesc.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_x_wfawlanconfigscpd, " >> $filename
echo "`stat -t xmldata_wps/x_wfawlanconfigscpd.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_x_wfa5Gdevicedesc, " >> $filename
echo "`stat -t xmldata_wps/x_wfa5Gdevicedesc.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_x_wfa5Gwlanconfigscpd, " >> $filename
echo "`stat -t xmldata_wps/x_wfa5Gwlanconfigscpd.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{XML_INDEX_InternetGatewayDevice2WLAN, " >> $filename
echo "`stat -t xmldata_wps/InternetGatewayDevice2WLAN.bin | cut -d ' ' -f 2`" >> $filename
echo "}," >> $filename

echo "{0 , 0}," >> $filename
echo "};" >> $filename





